### ISSUE TITLE
"RNPdfRendererView" was not found in the UIManager.

### ISSUE THREAD

**Issue by minuz** [douglasjunior/react-native-pdf-renderer#10]
- How did you link to the library (autolinking, manual, rn link, cocoapods)?
> Autolinking 
- What version of React Native?
> ` "react-native": "0.72.6"`
- What version of the library?
> `"react-native-pdf-renderer": "^1.2.0",`
- iOS/Android version?
> Both
- Did the problem happen after updating React Native?
> No
- Are you using the library for the first time?
> Yes
- It's a bug? Provide a link to a minimal reproduction case.
> Not sure. Followed the code sample
```
export function FileView() {
  const { fileUri, isFetching, actionLoading, footerProps, handleOnLayout } = useFileViewer();

  return (
    <AnimatedScrollLayout
      header={{ title: 'Test', showTitle: true, icon: DawnFiles }}
      footer={footerProps}
      onLayout={handleOnLayout}
      loadingProps={{
        isFetching: isFetching || actionLoading,
        bgColor: Colour.White[100],
        dotColor: 'dark',
      }}
      containerStyle={{ backgroundColor: Colour.White[100] }}
    >
      <PdfRendererView
        style={FileViewStyles.webView}
        source={fileUri}
        distanceBetweenPages={16}
        maxZoom={5}
      />
    </AnimatedScrollLayout>
  );
}
```
File download with `expo-file-system`
```
    try {
      setIsFetching(true);
      const fileLocation = getFilePath(fileName);
      const response = await FileSystem.downloadAsync(apiUrl, fileLocation, {
        headers: {
          Authorization: `Bearer ${token}`,
          Prefer: 'return=representation',
        },
      });

      setFileUri(response.uri);
    } catch (error) {
      captureException(error);
      Alert.alert('Error', 'There was an error downloading the file.');
    } finally {
      setIsFetching(false);
    }
```

Also, I'm running the app locally using Expo GO. Am I missing something on the setup? Any help would be appreciated!

**Comment by douglasjunior** [comment]
Seems that the native files are not linked when the library was installed.

Please make sure to run a `cd ios` and then `pod install` as mentioned in the [README](https://github.com/douglasjunior/react-native-pdf-renderer?tab=readme-ov-file#install).

**Comment by minuz** [comment]
We are using expo managed strategy. This means we don't have iOS and Android folders. All linking is done automatically by the expo engine.

**Comment by douglasjunior** [comment]
So, you need to read this to understand how to use third part libraries on the expo managed workflow.

https://docs.expo.dev/workflow/customizing/

**Comment by minuz** [comment]
@douglasjunior , Thank for you response. I suggest adding this to the limitations section on your readme so people don't spend time trying to figure it out something that won't work. =) 
Having to customise the native code means we cannot use this library with Expo Go. It probably works with the bare flow (ejecting the native projects). 
Again, thanks for taking the time to reply!

**Comment by douglasjunior** [comment]
This is not a limitation of the library, but of Expo.

In my view, anyone who chooses to work with expo needs to know the limitations of the platform.
