### ISSUE TITLE
Add top and bottom components

### ISSUE THREAD

**Issue by nonam4** [douglasjunior/react-native-pdf-renderer#11]
It would be nice if we could add components to be rendered before and after pdf content and this content will be scrolled with pdf.
E.g: If I render a button at bottom this button will only be visible when I reach the end of PDF content.

It will be something like this:
```
<Pdf 
  source='...' 
  header={<>This will be rendered before pdf</>}
  footer={<>This will only be visible when reach end of pdf content</>}
  ... other props
/>
```

I don't know if this is possible to be done but it's a nice feature

**Comment by douglasjunior** [comment]
About the need:

> E.g: If I render a button at bottom this button will only be visible when I reach the end of PDF content.

You can control the Button visibility by handling the current page index. So when the last page comes out you show de Button.

**Comment by nonam4** [comment]
> On Android may be possible, but I don't know if it will make sense to add an option that will work on just one platform.

Yes yes, makes no sense add a feature in only one platform, unfortunatelly. 

Thanks for your attention 😁
