### ISSUE TITLE
PDF resolution very low under Android

### ISSUE THREAD

**Issue by nmehlei** [douglasjunior/react-native-pdf-renderer#13]
When viewing a PDF inside Android (Android 14 was tested), the PDF resolution is very low. It's barely noticeable when the whole PDF page is displayed at once, but once you zoom in to actually read text, the text becomes very hard to read due to the text consisting mostly of pixels.

- How did you link to the library (autolinking, manual, rn link, cocoapods)?
autolinking

- What version of React Native?
0.73.5

- What version of the library?
1.2.0

- iOS/Android version?
Tested and found the issue under Android 14.
iOS Seems to be fine

- Did the problem happen after updating React Native?
No

- Are you using the library for the first time?
Yes

**Comment by douglasjunior** [comment]
Can you provide the PDF file to simulate the problem? 

Because as you can see with the PDF used in [Sample](https://github.com/douglasjunior/react-native-pdf-renderer/blob/main/Sample/App.tsx) project, everything looks fine.

**Comment by douglasjunior** [comment]
We found a situation in PDF that have low quality image captured from scanners.

Working progress solution https://github.com/douglasjunior/react-native-pdf-renderer/commit/7ba09b9ae9a0ea81bfa39b907e6ac8aaf0ff7842

**Comment by ergen35** [comment]
Have the same problem, under the same conditions except that i'm using RN 0.74.
It's such a lightweight an good PDF reader

**Comment by douglasjunior** [comment]
Hello guys, you can try this working in progress version with:

```
npm install react-native-pdf-renderer@https://github.com/douglasjunior/react-native-pdf-renderer.git#7ba09b9ae9a0ea81bfa39b907e6ac8aaf0ff7842
```

Or

```
yarn add react-native-pdf-renderer@https://github.com/douglasjunior/react-native-pdf-renderer.git#7ba09b9ae9a0ea81bfa39b907e6ac8aaf0ff7842
```

**Comment by douglasjunior** [comment]
Done https://github.com/douglasjunior/react-native-pdf-renderer/releases/tag/1.3.0
