### ISSUE TITLE
Load PDF from source

### ISSUE THREAD

**Issue by Aleksandar-FFWD** [douglasjunior/react-native-pdf-renderer#14]
Hello there 👋 

First of all, thanks for building such ha wonderful library!

I was wondering if it's possible to file from source code like we would do in case of an image

```
<PdfRendererView source={require('./path/to/file.pdf')} />
```

**Comment by douglasjunior** [comment]
I think yes, but I need to do some research to know how to get the absolute path from a JS `require`.
