### ISSUE TITLE
How to customize pages layout?

### ISSUE THREAD

**Issue by rmarquois** [douglasjunior/react-native-pdf-renderer#16]
Is there a way to customize pages layout?

If we look at Chromium's native rendering engine or Google Drive's preview, pages are (or can) be scaled relative to their container. You can either adjust to the screen size (although I think there is a maximum size), or adjust to the page height. 

### Fit to page height

![Capture d'écran 2024-06-14 161725](https://github.com/douglasjunior/react-native-pdf-renderer/assets/1659282/cc252077-f01d-4df7-99a9-7540bb57f25e)

### Fit to screen

![Capture d'écran 2024-06-14 162034](https://github.com/douglasjunior/react-native-pdf-renderer/assets/1659282/a0c998a2-14a9-4e60-a467-78dc6956e87a)

There are also margins for each page (for the moment your library only offers margins between pages).

I made some tests on Android in `PdfRendererRecyclerView` file but I'm not an expert ^^
For iOS, I see in PdfView documentation that we can configure display mode or scaling the view.

Do you plan to add this in your library?

**Comment by douglasjunior** [comment]
Currently, the page width always fit to the component width. 

Google Drive's preview is not designed to be used on Mobile, so the UX should be different.
