### ISSUE TITLE
Props for making text selectable (Feature Request)

### ISSUE THREAD

**Issue by nurulalamador** [douglasjunior/react-native-pdf-renderer#17]
There should be an props such "textSelectable" where we can set true or false. If it enabled, then we can copy text from PDF after it loaded.

**Comment by douglasjunior** [comment]
This is not possible on Android, because the PDF pages are rendered as images.

**Comment by douglasjunior** [comment]
https://github.com/douglasjunior/react-native-pdf-renderer/blob/4d707e774ae83e5313721d5e1957680eb79030f7/android/src/main/java/com/github/douglasjunior/reactNativePdfRenderer/modules/PdfRendererRecyclerView.java#L412-L437
