### ISSUE TITLE
Support Fabric and RCT_NEW_ARCH_ENABLED=1

### ISSUE THREAD

**Issue by Sowed** [douglasjunior/react-native-pdf-renderer#2]
Currently, the PDF loader component breaks if the new architecture/fabric is enabled in the project. Following error is displayed.

<img width="425" alt="image" src="https://user-images.githubusercontent.com/4072730/235164161-a32e3dbd-293c-44f5-b369-c3e6a6787521.png">

- How did you link to the library (autolinking, manual, rn link, cocoapods)?
pod install autolinks.
- What version of React Native?
Using RN `0.71.7`
- What version of the library?
`"react-native-pdf-renderer": "^1.0.5",`
- iOS/Android version?
Both Versions
- Did the problem happen after updating React Native?
Yes, Fabric and new Architecture support are related. Same issue observed in similar libs like `"react-native-pdf": "^6.6.2"`.
- Are you using the library for the first time?
YES
- It's a bug? Provide a link to a minimal reproduction case.
Not a bug per say, but a feature support request. To reproduce, bootstrap a fresh RN project with above version, and enable Fabric and new Architecture with `RCT_NEW_ARCH_ENABLED=1 pod install`

---

#PS, thank you for the lib.

**Comment by douglasjunior** [comment]
Yeah, I have tried to make it work with the new arch, but currently the documentation is pretty bad.

So, I can't make the events from native to JS work properly:

https://github.com/douglasjunior/react-native-pdf-renderer/blob/a90eedf55847aec6f5e7bfe7916a3694231535ca/android/src/main/java/com/github/douglasjunior/reactNativePdfRenderer/modules/PdfRendererRecyclerView.java#L114-L134

In my attempts I received errors that `receiveEvent` does not exist.

I noticed that there is a new implementation of `EventEmitter`, but I couldn't make it work either.

So, I gave up for now, until all this is more mature.
