### ISSUE TITLE
Handling links in pdf

### ISSUE THREAD

**Issue by idrakimuhamad** [douglasjunior/react-native-pdf-renderer#21]
My pdf have links inside. I wanted to handle its behaviour, so that when user pressed on it, I want to open it in the external browser. I see no prop to handle this.

**Comment by douglasjunior** [comment]
This is not possible on Android, because Android renders the page as full images.

To handle links, select texts, etc, I recommend to open the PDF in an external PDF Viewer.

**Comment by idrakimuhamad** [comment]
Thanks for the clarification. 👌
