### ISSUE TITLE
Crash Issue when double tap on pdf

### ISSUE THREAD

**Issue by ayanWappnet** [douglasjunior/react-native-pdf-renderer#25]
Here is my code for load pdf and i have crash issue when i double tap on pdf.can you please give me a suggestion for what should i do for that.

```
<View style={{ flex: 1, borderRadius: 24, overflow: 'hidden' }}>
          <PdfRendererView
            style={styles.pdf}
            source={source?.uri}
            maxZoom={6}
            singlePage={singlePage}
            distanceBetweenPages={16}
            onPageChange={(current, total) => {
              console.log('onPageChange', { current, total });
            }}
          />
        </View>
        
Style.tsx        
pdf: {
    backgroundColor: COLORS.primaryCheckThird,
  },
```

**Comment by douglasjunior** [comment]
Hi @ayanWappnet , please, provide more info about the crash:

- What is the platform and version? Android or iOS
- What is the version of React Native?
- What is the log error message?

Can you reproduce the crash with the code of [Sample project](https://github.com/douglasjunior/react-native-pdf-renderer/tree/main/Sample)?

Just clone this repo and:

```sh
cd Sample
./install.sh
```

**Comment by ayanWappnet** [comment]
Hello @douglasjunior 
platform:Android 
react-native version : 0.72.6 
no any log error

```
<View style={{ flex: 1, borderRadius: 24, overflow: 'hidden' }}>
          <PdfRendererView
            style={styles.pdf}
            source={source?.uri}
            maxZoom={6}
            singlePage={singlePage}
            distanceBetweenPages={16}
            onPageChange={(current, total) => {
              console.log('onPageChange', { current, total });
            }}
          />
        </View>
        
Style.tsx        
pdf: {
    backgroundColor: COLORS.primaryCheckThird,
  },
```

**Comment by douglasjunior** [comment]
If you have a crash, then should have a log error.

Probably there should be a native error on the Java side, so you need to use the Android Studio logcat to see them.

Debugging Native Code: https://reactnative.dev/docs/debugging-native-code
