### ISSUE TITLE
Android device scrolling not working

### ISSUE THREAD

**Issue by InxUser** [douglasjunior/react-native-pdf-renderer#28]
- How did you link to the library (autolinking, manual, rn link, cocoapods)?
Autolinking

- What version of React Native?
0.74.5

- What version of the library?
^1.4.0

- iOS/Android version?
Android OS Version 34

- Did the problem happen after updating React Native?
No

- Are you using the library for the first time?
Yes

- It's a bug? Provide a link to a minimal reproduction case.
 scrolling in android device is not working

**Comment by douglasjunior** [comment]
Have you checked the styling in the parent component? Please take a look at the [limitations section](https://github.com/douglasjunior/react-native-pdf-renderer?tab=readme-ov-file#size-measuring) on the README.
