### ISSUE TITLE
File Not In PDF Format Or Corrupted

### ISSUE THREAD

**Issue by ikotsov** [douglasjunior/react-native-pdf-renderer#29]
I am experiencing this error only in Android. In iOS it works as expected. In release builds, the app crashes, in debug builds I get this error:
![Screenshot_2024-10-30_at_3 19 34_PM](https://github.com/user-attachments/assets/a8c76345-0bcf-46a2-8839-d6cab77b42ba)

This is exactly the code I am using. I fetch a pdf from an external source, and then I manipulate the blob data in order to create a file locally into the app sandbox using expo filesystem and then provide the src path to the pdf library.

```
import * as FileSystem from 'expo-file-system';
import { useEffect, useState } from 'react';
import { ActivityIndicator } from 'react-native';
import PdfRendererView from 'react-native-pdf-renderer';

import { useExamDetailsContext } from './ExamDetailsProvider';

import { useExamPdf } from '@/services/exams';

export const PdfView = () => {
  const [hasSavedFileLocally, setHasSavedFileLocally] = useState(false);
  const details = useExamDetailsContext();

  const { data, isPending, isError } = useExamPdf(details.id);

  const fileUri = FileSystem.documentDirectory + `${details.id}.pdf`;
  useEffect(() => {
    if (!data) return;

    const savePdfToFileSystem = async () => {
      const reader = new FileReader();

      reader.onloadend = async () => {
        if (!reader.result || typeof reader.result !== 'string') return;

        // Accesses the second part of the Base64 url, which is the actual Base64-encoded PDF content.
        const base64Data = reader.result.split(',')[1];
        FileSystem.writeAsStringAsync(fileUri, base64Data, {
          encoding: FileSystem.EncodingType.Base64
        });
        setHasSavedFileLocally(true);
      };

      reader.readAsDataURL(data);
    };

    savePdfToFileSystem();

    return () => {
      FileSystem.deleteAsync(fileUri);
    };
  }, [data, fileUri]);

  if (isPending || !hasSavedFileLocally) return <ActivityIndicator />;

  if (isError) return null;

  return <PdfRendererView source={fileUri} />;
};

```

I have also checked the [sample project](https://github.com/douglasjunior/react-native-pdf-renderer/blob/main/Sample/App.tsx), and the code seems to be quite similar.

Any thoughts why this might happening?

- How did you link to the library (autolinking, manual, rn link, cocoapods)?
cocoapods
- What version of React Native?
Expo SDK 51, React Native 0.74
- What version of the library?
latest: 1.4.0
- iOS/Android version?
Android
- Did the problem happen after updating React Native?
Nope
- Are you using the library for the first time?
Yes
- It's a bug? Provide a link to a minimal reproduction case.
I am not sure but it seems to be a bug.

**Comment by douglasjunior** [comment]
Have you writing the file as base64? If so, this is probably the problem.

In any case, try to call setHasSavedFileLocally(true); only after the writeAsStringAsync complete, because it's async.

**Comment by ikotsov** [comment]
> Have you writing the file as base64? If so, this is probably the problem. The file should be in binary.
> 
> In any case, try to call setHasSavedFileLocally(true); only after the writeAsStringAsync complete, because it's async.

Great catch! That was it, it seems that the package works fine!

Yes, I am writing the file as base64, the expo file system accepts either a UTF8 or base64 encoding.

**Comment by douglasjunior** [comment]
No problem.
