### ISSUE TITLE
Scrolling is too fast when zoomed in

### ISSUE THREAD

**Issue by m-anshuman2166** [douglasjunior/react-native-pdf-renderer#3]
Whenever I zoom in the pdf and try scrolling, the pdf scrolls too fastly

Demo :

https://github.com/douglasjunior/react-native-pdf-renderer/assets/72782632/e323ebb9-783c-471d-9d35-7c62214680e8

Kindly try to make the scrolling speed normal when the pdf is zoomed it

**Comment by douglasjunior** [comment]
Yes, unfortunately on Android this is expected because the zoom stretches the View and consequently multiplying the scrolling speed.

The solution is to not allow too high a zoom level.

**Comment by douglasjunior** [comment]
@m-anshuman2166 please, can you try with version `1.1.0-beta.2`?

I made some updates to remove the exponential speed on Android.

**Comment by douglasjunior** [comment]
@m-anshuman2166 about the page number, please take a look at the [Sample project](https://github.com/douglasjunior/react-native-pdf-renderer/blob/main/Sample/App.tsx).

**Comment by douglasjunior** [comment]
I prefer to keep the PDF download responsibility outside the library, as in React Native this can be done in many ways.

Btw released version `1.1.0`.
