### ISSUE TITLE
[1.5.0] Can't load local PDF file with RN 0.76

### ISSUE THREAD

**Issue by TomCorvus** [douglasjunior/react-native-pdf-renderer#36]
Hello, 
- Auto
- RN 0.76.3
- 1.5.0
- Android
- Don't know
- No
- https://github.com/TomCorvus/RNavigation/tree/PDFrenderer

Since 1.5.0, I can't open PDF files on Android with RN0.76. Downgrade to 1.4.0 version fix the problem.
![Screenshot_1734531709](https://github.com/user-attachments/assets/d0ab026c-05d8-4d2b-ab8f-263c2e893951)

No issue on iOS.

**Comment by douglasjunior** [comment]
Fixed in version 1.5.1
