### ISSUE TITLE
ArithmeticException - divide by zero

### ISSUE THREAD

**Issue by Rishabh20051997** [douglasjunior/react-native-pdf-renderer#6]
On Certain devices getting Issue
`com.github.douglasjunior.reactNativePdfRenderer.modules.b in onSizeChanged at line 6`

Mostly reported on Android 11 devices.

react-native-pdf-renderer - 1.1.1
react - 18.2.0
react-native - 0.71.5

**Comment by douglasjunior** [comment]
To throw an `ArithmeticException - divide by zero` exception the `height or width` of your view needs to be zero.

https://github.com/douglasjunior/react-native-pdf-renderer/blob/c1bfb441976127395e7eea4945e395868d41cd84/android/src/main/java/com/github/douglasjunior/reactNativePdfRenderer/modules/PdfRendererRecyclerView.java#L159

This is a requirement [listed on README](https://github.com/douglasjunior/react-native-pdf-renderer#size-measuring), please double-check your layout.

**Comment by douglasjunior** [comment]
I will add a validation to prevent `divide by zero` on this line, but we can't guarantee that you will not find other issues.

**Comment by master429** [comment]
> I will add a validation to prevent `divide by zero` on this line, but we can't guarantee that you will not find other issues.我将添加一个验证来防止 `divide by zero` 这一行，但我们不能保证你不会发现其他问题。

Does the library support rendering of base64 assets？

**Comment by douglasjunior** [comment]
> Does the library support rendering of base64 assets？

Probably you will need to write the base64 to the file system, and then set the file URL on the PdfRenderer.

Try something like this if you are using expo-file-system:

```js
const data = "ASDFASDFASDf........"

const filename = FileSystem.documentDirectory + "some_unique_file_name.pdf";
await FileSystem.writeAsStringAsync(filename, data, {
  encoding: FileSystem.EncodingType.Base64,
});
```

And then:

```jsx
  <PdfRendererView
            source={filename}
  />
```
