### ISSUE TITLE
IllegalStateException - cannot load page

### ISSUE THREAD

**Issue by Rishabh20051997** [douglasjunior/react-native-pdf-renderer#7]
Facing issues with certain Users - 
android.graphics.pdf.PdfRenderer in nativeOpenPageAndGetSize

react-native-pdf-renderer - 1.1.1
react - 18.2.0
react-native - 0.71.5

Requirement :
Please provide a callback such as `onError` to handle such a case.

**Comment by douglasjunior** [comment]
We don't use `nativeOpenPageAndGetSize` directly in our code, please provide the complete stack trace of the exception.

**Comment by arturspon** [comment]
Same problem here, if you want here's the Sentry link to the stacktrace: https://convicti.sentry.io/share/issue/58db09f8d7a940b5b83504c80eda19ac/

**Comment by douglasjunior** [comment]
Please update to the latest lib version and if the problem persists open a new issue with more information about lib version, android version, new or old arch, etc. 

We have fixed some crashes recently that probably will solve this issue too.
